#Minecraft server properties
#Wed May 13 20:39:50 MSK 2026
level-name=world
motd=A Minecraft Server
view-distance=10
white-list=false
server-ip=
pvp=true
spawn-npcs=true
level-seed=
spawn-animals=true
server-port=25565
gamemode=0
generate-structures=true
enable-rcon=false
difficulty=1
enable-query=false
level-type=DEFAULT
spawn-monsters=true
max-players=20
online-mode=true
allow-flight=false
